### PR TITLE
[内容修订] 修正部分 `:` <=> `<br>` 问题

### LINKED ISSUE #963: [PAGE ISSUE]: '创建响应式和自适应的应用'
### 页面 URL

https://flutter.cn/docs/development/ui/layout/adaptive-responsive/

### 页面源地址

https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/layout/adaptive-responsive.md

### 描述问题

部分中英对照显示效果不正常。
image

### 期望如何修复

_No response_

### 附加信息

查阅了Wiki但没有看出来问题在哪。

### PR DESCRIPTION
**Pull request by AlexV525**
### 解决的 Issues

Fix #963 .

### 更新内容描述

`: ` 替换为 `<br> `。

### CODE REVIEW

**Comment by CCXXXI** [comment]
原来英文也要替换，Wiki的描述比较有误导性。

还有另外几页有类似问题 ([ios.md](https://github.com/cfug/flutter.cn/tree/master/src/docs/deployment/ios.md), [vs-code.md](https://github.com/cfug/flutter.cn/tree/master/src/docs/development/tools/vs-code.md), [implicit-animations.md](https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/animations/implicit-animations.md), etc.)，弄个自动替换可能好一点？

**Comment by AlexV525** [comment]
> 还有另外几页有类似问题 ([ios.md](https://github.com/cfug/flutter.cn/tree/master/src/docs/deployment/ios.md), [vs-code.md](https://github.com/cfug/flutter.cn/tree/master/src/docs/development/tools/vs-code.md), [implicit-animations.md](https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/animations/implicit-animations.md), etc.)，弄个自动替换可能好一点？

规则比较复杂，可以列出来能找到的页面吗？

**Comment by CCXXXI** [comment]
> > 还有另外几页有类似问题 ([ios.md](https://github.com/cfug/flutter.cn/tree/master/src/docs/deployment/ios.md), [vs-code.md](https://github.com/cfug/flutter.cn/tree/master/src/docs/development/tools/vs-code.md), [implicit-animations.md](https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/animations/implicit-animations.md), etc.)，弄个自动替换可能好一点？
> 
> 规则比较复杂，可以列出来能找到的页面吗？

用正则表达式 `^:` 可以搜到以下文件：

1. [web.md](https://github.com/cfug/flutter.cn/blob/master/src/web.md)
2. [introduction.md](https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/testing/widget/introduction.md)
3. [ios.md](https://github.com/cfug/flutter.cn/blob/master/src/docs/deployment/ios.md)
4. [linux.md](https://github.com/cfug/flutter.cn/blob/master/src/docs/deployment/linux.md)
5. [obfuscate.md](https://github.com/cfug/flutter.cn/blob/master/src/docs/deployment/obfuscate.md)
6. [developing-packages.md](https://github.com/cfug/flutter.cn/blob/master/src/docs/development/packages-and-plugins/developing-packages.md)
7. [vs-code.md](https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/vs-code.md)
8. [implicit-animations.md](https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/animations/implicit-animations.md)
9. [adaptive-responsive.md](https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/layout/adaptive-responsive.md)
10. [scrollable-alert-dialog.md](https://github.com/cfug/flutter.cn/blob/master/src/docs/release/breaking-changes/scrollable-alert-dialog.md)
11. [faq.md](https://github.com/cfug/flutter.cn/blob/master/src/docs/resources/faq.md)

看了下都是差不多的情况，有些虽然还没有翻译，但提前换掉似乎也可以。

**Comment by CCXXXI** [comment]
使用直角引号是强制性规范吗？排版指南仅将其列在了 [争议](https://github.com/cfug/flutter.cn/wiki/%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%88%E6%8E%92%E7%89%88%E6%8C%87%E5%8D%97-(Chinese-Typography-Guide)#%E4%BA%89%E8%AE%AE) 章节下而没有指明是否采纳；站内文档目前是混用状态。

**Comment by AlexV525** [comment]
新的文档全部以直角引号为准。

**Comment by CCXXXI** [comment]
> 新的文档全部以直角引号为准。

旧的文档应该保留原样还是替换掉？

**Review by chenglu — APPROVED** [review]

**Pull request merged**
